### PR TITLE
Requesting Code Review

### PR DESCRIPTION
**Pull request by kylebaron**
Primary functionality has been coded and tests written according to issues #1, #2, #3 

Requesting code review; I will respond to review items in this pull request and, once the PR is reviewed I will merge into the `dev` branch.  

At that point, I will consider the code reviewed and will start validation procedure per the SDLC.

### CODE REVIEW

**Review by Dreznel — APPROVED** [review]
LGTM, but are there supposed to be code changes in this PR?

After looking at the overall code, which I can't review on this PR page, my only comment is:

1) In the `lastdose_impl` function of `lastdose.cpp`, it would improve readability to break out some of the nested `for` loops into their own function. Not sure how necessary this is since this an Rcpp function, which I don't see us modifying a lot in the future, but a good practice to adopt in general.

**Comment by Dreznel** [comment]
Also it looks like Dev is out of sync with master, should this just be changed to point directly at master?

**Comment by kylebaron** [comment]
Thanks @Dreznel ;  Yes, please do consider all of the code.  This was a personal development project that I have brought into Metrum and couldn't think of a way to get all of the code up for review in the pr.  Just trying to get it into the SDLC cycle at this point. If there are other issues, please bring them up here.  Also happy to follow suggestions for git strategy form making all of the code show up in the diff for the PR.

**Comment by Dreznel** [comment]
Just confirming that I didn't see any other major issues. Maybe a few of your variable/function names could be more descriptive, but for the time being that comes down to personal preference, and I tend to be very verbose in that regard so I think you're fine.

As for making all the code show up in a diff, I would say just don't worry about it -- we can just review the code without the GitHub tooling on the first pass, and from then on we can focus only one what's updated.

**Comment by kylebaron** [comment]
Thanks!

**Pull request merged**
